### ISSUE TITLE
Elixir implementation?

### ISSUE THREAD

**Issue by s3cur3** [mhsjlw/node-raknet#32]
I know this isn't the proper forum for this, and I apologize for that... but for the life of me I couldn't figure out any other means of contacting @mhsjlw.

A couple years ago, you had an elixir-raknet library, but it appears to have disappeared from the internets. Do you by chance have an archive of it lying around? I'm working on an Elixir RakNet client now, and would be *very* grateful to get a head start, even if your project was killed before being production-grade.

**Comment by mhsjlw** [comment]
Yeah, I'll send it your way. Just be warned the code is no good which is why I took it down in the first place.

The code is here: https://github.com/mhsjlw/ExRakLib

You have my _explicit_ written permission right here that you or anyone else may use this code for any purpose (e.g.: it is _not_ under the AGPL license that is listed in the repository). I am releasing it into the public domain, or the [Unlicense](https://unlicense.org/) (if public domain does not exist in your legal jurisdiction).

If this is not enough for your purposes, I am willing to change the license file in the repository if need be.

**Comment by s3cur3** [comment]
Holy cow. Thanks so much! It'll be awesome as a reference if nothing else.

Best wishes.

**Comment by s3cur3** [comment]
Hi @mhsjlw,

I've been hammering on this for a couple weeks now, and I think I have something that might be useful to other people (if not now, certainly by the time I'm using it in production in a few months).

Would you prefer I set it up as its own project, or a fork of your ExRakLib?

**Comment by mhsjlw** [comment]
I think setting it up as a separate project is the best idea, then I'd be happy to link it in the README of the ExRakLib repository. Good to hear it's been of use!

**Comment by mhsjlw** [comment]
For my own curiosity: has an improved version been released?

**Comment by s3cur3** [comment]
@mhsjlw Yes, finally! 😄 

https://github.com/X-Plane/elixir-raknet

**Comment by mhsjlw** [comment]
Awesome! I am very happy to see it grew into something useful :smile:. Best of luck with the X-Plane MMO project.
